name: Junction-VIII-Catalogs-Check

run-name: 1.0.0.${{ github.run_number }}

on:
  pull_request:
    branches:
      - master

env:
  _IS_BUILD_CANARY: false
  _IS_GITHUB_RELEASE: false
  _RELEASE_NAME: JunctionVIIICatalogs
  _RELEASE_VERSION: v0
  _BUILD_BRANCH: "${{ github.ref }}"
  _BUILD_VERSION: "1.0.0.${{ github.run_number }}"
  GIT_REDIRECT_STDERR: 2>&1

jobs:
  CI:
    runs-on: ubuntu-latest 
    timeout-minutes: 1440
    strategy:
      max-parallel: 1
    steps:
      - name: Set Git Config
        run: |
          git config --global core.autocrlf false
          git config --global core.filemode false
          git config --global core.longpaths true
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
      - name: Set execute permission for prepare.sh
        run: chmod +x .github/workflows/prepare.sh
      - name: Prepare Env
        run: .github/workflows/prepare.sh
        shell: bash
      - name: Block changes to tsunamods.xml
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'catalogs/tsunamods.xml'; then
            echo "Changes to catalogs/tsunamods.xml are not allowed."
            exit 1
          fi
      - name: Set execute permission for validate.sh
        run: chmod +x .github/workflows/validate.sh
      - name: Run Validation
        run: .github/workflows/validate.sh